#if !defined(AFX_XNET_H__68D46A0D_78ED_4ABF_88A9_9648BC4A117E__INCLUDED_)
#define AFX_XNET_H__68D46A0D_78ED_4ABF_88A9_9648BC4A117E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CXNet wrapper class

class CXNet : public CWnd
{
protected:
	DECLARE_DYNCREATE(CXNet)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa3297bf4, 0x7819, 0x47ac, { 0x9b, 0x10, 0xb2, 0x43, 0x52, 0x3c, 0x29, 0xc7 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetIp();
	void SetIp(LPCTSTR);
	long GetPort();
	void SetPort(long);
	BOOL GetActive();
	void SetActive(BOOL);
	BOOL GetSpoolEnabled();
	void SetSpoolEnabled(BOOL);
	long GetMaxSpoolSize();
	void SetMaxSpoolSize(long);
	CString GetSpoolDir();
	void SetSpoolDir(LPCTSTR);
	BOOL GetLogEvent();
	void SetLogEvent(BOOL);
	BOOL GetLogMesgSummary();
	void SetLogMesgSummary(BOOL);
	BOOL GetLogMesgDetail();
	void SetLogMesgDetail(BOOL);
	BOOL GetEstablished();
	void SetEstablished(BOOL);
	long GetSendTimeout();
	void SetSendTimeout(long);

// Operations
public:
	long SendString(LPCTSTR szStrVal, long nLen);
	CString GetString(long lMsgID);
	long Start();
	long Stop();
	long PurgeSpool();
	long GetBinary(long lMsgID, short* pByteBuff, long nBuffCount);
	long SendBinary(short* pByteBuff, long nCount);
	long GetLastError();
	CString GetLastErrorString();
	CString GetErrorString(long nError);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_XNET_H__68D46A0D_78ED_4ABF_88A9_9648BC4A117E__INCLUDED_)
