/* Generated by Together */
#include "stdafx.h"
#include "MTowerLampData.h"
#include "MyProgressWnd.h"
#include "MSystemData.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

MTowerLampData::MTowerLampData(CString strFileName) : MFileManager(strFileName)
{
	Initialize();				// 멤버 변수 초기화
}
MTowerLampData::MTowerLampData(CString strFileName, CString strPath): MFileManager(strFileName, strPath)
{
	Initialize();				// 멤버 변수 초기화
}
void MTowerLampData::Initialize()
{
	m_bUseRedLamp_NomalRun =  FALSE;
	m_bUseRedLamp_StepStop =  FALSE;
	m_bUseRedLamp_ErroeStop =  FALSE;
	m_bUseRedLamp_PanelEmpty =  FALSE;
	m_bUseRedLamp_MaterialChange =  FALSE;
	m_bUseRedLamp_OPCall =  FALSE;

	m_bUseYellowLamp_NomalRun =  FALSE;
	m_bUseYellowLamp_StepStop =  FALSE;
	m_bUseYellowLamp_ErroeStop =  FALSE;
	m_bUseYellowLamp_PanelEmpty =  FALSE;
	m_bUseYellowLamp_MaterialChange =  FALSE;
	m_bUseYellowLamp_OPCall =  FALSE;

	m_bUseGreenLamp_NomalRun =  FALSE;
	m_bUseGreenLamp_StepStop =  FALSE;
	m_bUseGreenLamp_ErroeStop =  FALSE;
	m_bUseGreenLamp_PanelEmpty =  FALSE;
	m_bUseGreenLamp_MaterialChange =  FALSE;
	m_bUseGreenLamp_OPCall =  FALSE;

	m_bUseBuzzer_NomalRun =  FALSE;
	m_bUseBuzzer_StepStop =  FALSE;
	m_bUseBuzzer_ErroeStop =  FALSE;
	m_bUseBuzzer_PanelEmpty =  FALSE;
	m_bUseBuzzer_MaterialChange =  FALSE;
	m_bUseBuzzer_OPCall =  FALSE;

	m_bUseStartLamp_NomalRun =  FALSE;
	m_bUseStartLamp_StepStop =  FALSE;
	m_bUseStartLamp_ErroeStop =  FALSE;
	m_bUseStartLamp_PanelEmpty =  FALSE;
	m_bUseStartLamp_MaterialChange =  FALSE;
	m_bUseStartLamp_OPCall =  FALSE;

	m_bUseStopLamp_NomalRun =  FALSE;
	m_bUseStopLamp_StepStop =  FALSE;
	m_bUseStopLamp_ErroeStop =  FALSE;
	m_bUseStopLamp_PanelEmpty =  FALSE;
	m_bUseStopLamp_MaterialChange =  FALSE;
	m_bUseStopLamp_OPCall =  FALSE;

}

MTowerLampData::~MTowerLampData()
{

}

BOOL MTowerLampData::ReadData()
{
	char		eMsg[200];
	char		eMsg1[200];
	BOOL		ret = TRUE;
	CString		szBuff;

	CString szTextTemp1;
	CString szTextTemp2;
	CString szTitleTemp;

	memset(eMsg, 0, sizeof(eMsg));
	memset(eMsg1, 0, sizeof(eMsg1));


	if(!GetValue(m_strSection, _T("Use_RedLamp_NomalRun"), &m_bUseRedLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15001"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_RedLamp_StepStop"), &m_bUseRedLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15003"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_RedLamp_ErrorStop"), &m_bUseRedLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15005"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_RedLamp_PanelEmpty"), &m_bUseRedLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15007"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_RedLamp_MaterialChange"), &m_bUseRedLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15009"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("UseRedLamp_OPCall"), &m_bUseRedLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15010"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_YellowLamp_NomalRun"), &m_bUseYellowLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15011"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_YellowLamp_StepStop"), &m_bUseYellowLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15013"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_YellowLamp_ErrorStop"), &m_bUseYellowLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15015"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_YellowLamp_PanelEmpty"), &m_bUseYellowLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15017"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_YellowLamp_MaterialChange"), &m_bUseYellowLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15019"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("UseYellowLamp_OPCall"), &m_bUseYellowLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15020"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_GreenLamp_NomalRun"), &m_bUseGreenLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15021"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_GreenLamp_StepStop"), &m_bUseGreenLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15023"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_GreenLamp_ErrorStop"), &m_bUseGreenLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15025"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_GreenLamp_PanelEmpty"), &m_bUseGreenLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15027"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_GreenLamp_MaterialChange"), &m_bUseGreenLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15029"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("UseGreenLamp_OPCall"), &m_bUseGreenLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15030"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_Buzzer_NomalRun"), &m_bUseBuzzer_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15031"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_Buzzer_StepStop"), &m_bUseBuzzer_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15032"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_Buzzer_ErrorStop"), &m_bUseBuzzer_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15033"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_Buzzer_PanelEmpty"), &m_bUseBuzzer_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15034"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_Buzzer_MaterialChange"), &m_bUseBuzzer_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15035"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("UseBuzzer_OPCall"), &m_bUseBuzzer_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15036"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StartLamp_NomalRun"), &m_bUseStartLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15037"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StartLamp_StepStop"), &m_bUseStartLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15038"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StartLamp_ErrorStop"), &m_bUseStartLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15039"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StartLamp_PanelEmpty"), &m_bUseStartLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15040"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StartLamp_MaterialChange"), &m_bUseStartLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15041"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("UseStartLamp_OPCall"), &m_bUseStartLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15042"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StopLamp_NomalRun"), &m_bUseStopLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15043"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StopLamp_StepStop"), &m_bUseStopLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15044"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StopLamp_ErrorStop"), &m_bUseStopLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15045"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StopLamp_PanelEmpty"), &m_bUseStopLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15046"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("Use_StopLamp_MaterialChange"), &m_bUseStopLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15047"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!GetValue(m_strSection, _T("UseStopLamp_OPCall"), &m_bUseStopLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15048"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}


	return ret;
}

BOOL MTowerLampData::WriteData()
{
	char eMsg[200];
	char eMsg1[200];
	BOOL ret = TRUE;
	CString strSection;
	memset(eMsg, 0, sizeof(eMsg));
	memset(eMsg1, 0, sizeof(eMsg1));

	CString szTextTemp1;
	CString szTextTemp2;
	CString szTitleTemp;

	if(!SetValue(m_strSection, _T("Use_RedLamp_NomalRun"), m_bUseRedLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15049"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_RedLamp_StepStop"), m_bUseRedLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15050"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_RedLamp_ErrorStop"), m_bUseRedLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15051"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_RedLamp_PanelEmpty"), m_bUseRedLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15052"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_RedLamp_MaterialChange"), m_bUseRedLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15053"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("UseRedLamp_OPCall"), m_bUseRedLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15054"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_YellowLamp_NomalRun"), m_bUseYellowLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15055"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_YellowLamp_StepStop"), m_bUseYellowLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15056"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_YellowLamp_ErrorStop"), m_bUseYellowLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15057"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_YellowLamp_PanelEmpty"), m_bUseYellowLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15058, &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_YellowLamp_MaterialChange"), m_bUseYellowLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15059", &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("UseYellowLamp_OPCall"), m_bUseYellowLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15060"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_GreenLamp_NomalRun"), m_bUseGreenLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15061"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_GreenLamp_StepStop"), m_bUseGreenLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15062"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_GreenLamp_ErrorStop"), m_bUseGreenLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15063"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_GreenLamp_PanelEmpty"), m_bUseGreenLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15064"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_GreenLamp_MaterialChange"), m_bUseGreenLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15065"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("UseGreenLamp_OPCall"), m_bUseGreenLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15066"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_Buzzer_NomalRun"), m_bUseBuzzer_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15067"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_Buzzer_StepStop"), m_bUseBuzzer_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15068"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_Buzzer_ErrorStop"), m_bUseBuzzer_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15069"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_Buzzer_PanelEmpty"), m_bUseBuzzer_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15070"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_Buzzer_MaterialChange"), m_bUseBuzzer_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15071"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("UseBuzzer_OPCall"), m_bUseBuzzer_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15072"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StartLamp_NomalRun"), m_bUseStartLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15073"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StartLamp_StepStop"), m_bUseStartLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15074"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StartLamp_ErrorStop"), m_bUseStartLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15075"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StartLamp_PanelEmpty"), m_bUseStartLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15076"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StartLamp_MaterialChange"), m_bUseStartLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15077"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("UseStartLamp_OPCall"), m_bUseStartLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15078"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StopLamp_NomalRun"), m_bUseStopLamp_NomalRun))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15079"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StopLamp_StepStop"), m_bUseStopLamp_StepStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15080"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StopLamp_ErrorStop"), m_bUseStopLamp_ErroeStop))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15081"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StopLamp_PanelEmpty"), m_bUseStopLamp_PanelEmpty))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15082"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("Use_StopLamp_MaterialChange"), m_bUseStopLamp_MaterialChange))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15083"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	if(!SetValue(m_strSection, _T("UseStopLamp_OPCall"), m_bUseStopLamp_OPCall))
	{
		ReadDisplayMessage(MY_MESSAGE_BOX, _T("Message_15084"), &szTextTemp1);
		szTextTemp2.Format(_T("[%s] %s"),m_strSection,szTextTemp1);
		szTitleTemp.Format(_T("[%s] File Read Error"),m_strFileName);
		if (MyMessageBox(szTextTemp2, (LPCTSTR)szTitleTemp, M_ICONERROR|M_YESNO) == IDNO) return FALSE;
		ret = FALSE;
	}

	return ret;
}

/* End Of Code */
