// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "texture.h"


/////////////////////////////////////////////////////////////////////////////
// CTexture properties

CString CTexture::GetFilepath()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CTexture::SetFilepath(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

long CTexture::GetMode()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CTexture::SetMode(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

short CTexture::GetLightIntensity()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CTexture::SetLightIntensity(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

unsigned long CTexture::GetColorToMix()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CTexture::SetColorToMix(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

short CTexture::GetPercentageColorMix()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CTexture::SetPercentageColorMix(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CTexture operations
