/* Generated by Together */

#ifndef CQUEUE_H
#define CQUEUE_H

//---------------------------- 상수 정의 --------------------------//
#define    BUFF_SIZE		8192

class CQueue {
public:    

    CQueue(); 
	
	//@121210.KKY____________
	void SetEndChar(BYTE cEnd);
	BYTE GetEndChar();
	//@______________________

    BOOL HaveString();

    void Clear();

    int GetSize();

    /**
     * 1 byte 넣기 
     */
    BOOL PutByte(BYTE b);

    /**
     * 1 byte 꺼내기 
     */
    BOOL GetByte(BYTE* pb);

private:
	BYTE m_cEndChar;

    BYTE buff[BUFF_SIZE];
    int m_iHead;
    int m_iTail;
};
#endif //CQUEUE_H
