/* Generated by Together */

#include "stdafx.h"
#include "CQueue.h"
#include "DefSerialValue.h"

CQueue::CQueue()
{
	Clear();
	m_cEndChar = '\r';
}

//@121210.KKY____________
void CQueue::SetEndChar(BYTE cEnd)
{
	m_cEndChar = cEnd;
}

BYTE CQueue::GetEndChar()
{
	return m_cEndChar;
}
//@______________________

BOOL CQueue::HaveString()
{
	if (GetSize() == 0) return FALSE;
	else
	{
		for(int i = m_iTail; i != m_iHead; i++)
		{
			i %= BUFF_SIZE;
//@			if(buff[i] == '\r')
			if (m_cEndChar != NOTUSE)
			{
				if(buff[i] == m_cEndChar)
					return TRUE;
			}
			else
			{
				if(buff[i] != 0 && buff[i+1] == 0)
					return TRUE;
			}
		}
	}
	return FALSE;
}

void CQueue::Clear()
{
	m_iHead = m_iTail = 0;
	memset(buff, 0, BUFF_SIZE);
}

int CQueue::GetSize()
{
	return (m_iHead - m_iTail + BUFF_SIZE) % BUFF_SIZE;
}

BOOL CQueue::PutByte(BYTE b)
{
	if (GetSize() == (BUFF_SIZE - 1)) return FALSE;
	buff[m_iHead++] = b;
	m_iHead %= BUFF_SIZE;
	return TRUE;
}

BOOL CQueue::GetByte(BYTE* pb)
{
	if (GetSize() == 0) return FALSE;
	*pb = buff[m_iTail++];
	m_iTail %= BUFF_SIZE;
	return TRUE;
}
