/* Generated by Together */

#ifndef ICOMTHREAD_H
#define ICOMTHREAD_H

#include "ICommon.h"

/**
 * @stereotype interface 
 */
class IComThread   : public virtual ICommon
{
public:
	virtual ~IComThread(){};

public:
    /**
     * 포트 열기 : OpenPort("COM1", CBR_9600); 
     */
    virtual int OpenPort() = 0;

    virtual int ClosePort() = 0;

    /**
     * WriteComm(buff, 30)과 같이 버퍼와 그 크기를 건네면 된다. 
     */
    virtual int WriteComm(BYTE * pBuff, DWORD nToWrite) = 0;

    /**
     * 포트를 연 후에 포트에 자료가 도착하면 WM_COMM_READ 메시지가 메인 
     * 윈도우에 전달된다. ON_MESSAGE 매크로를 이용, 함수를 연결하고
     *  m_ReadData String에 저장된 데이터를 이용 읽기 
     */
    virtual int ReadComm(BYTE * pBuff, DWORD nToRead) = 0;

    virtual int ReceiveData(unsigned char * buf, int iBufSize) = 0;

    virtual int SendData(unsigned char * buf) = 0;

    virtual int ReceiveData(char * buf, int iBufSize) = 0;

    virtual int SendData(char * buf) = 0;

	virtual	int RestartThread() = 0;

	virtual int PauseThread() = 0;

	virtual void ClearRecvQueue() = 0;

	virtual int GetPortNo() = 0;

};
#endif //ICOMTHREAD_H
