/* Generated by Together */

#ifndef MVacuum_H
#define MVacuum_H

#include "IVacuum.h"

#ifdef SIMULATION
#	include "MTickTimer.h"
#endif

class MVacuum : public IVacuum
{
private:
	int m_iVacID;
	
	CString m_strVacuumName;

	/** Vacuum을 제어하는 Solenoid들의 I/O Address들에 대한 포인터 */
	unsigned short m_rgusSolenoid[DEF_MAX_VACUUM_SOLENOID];

	/** Vacuum의 흡착 상태를 확인하는 Sensor들의 I/O Address들에 대한 포인터 */
	unsigned short m_rgusSensor[DEF_MAX_VACUUM_SOLENOID];

	/** @link aggregation Vacuum Type */
	EVacuumType m_eVacuumType;

	/** Vacuum Data가 저장될 File Name */
	CString m_strFileName;

	MVacuumData m_VacParameter;

#ifdef SIMULATION
	/** Simulation 동작 시에 Vacuum On 상태를 확인하기 위한 flag */
	BOOL m_bSimulOnState;

	/** Simulation Mode 에서 Vacuum On 동작 진행 중 상태 표시 flag */
	BOOL m_bVacuumOnBeingOnState;
	/** Simulation Mode 에서 Vacuum Off 동작 진행 중 상태 표시 flag */
	BOOL m_bVacuumOnBeingOffState;

	/** Simulation 동작 시에 Vacuum 동작 시간 Check Timer */
	MTickTimer m_tmSimulTimer;

	CRITICAL_SECTION m_csSimul;
#endif

public:
	/** Default 생성자 */
	MVacuum();

	MVacuum(SCommonAttribute commonData, IIO *pIIO, SVacuumData datComponent);

	virtual ~MVacuum();

	int GetVacuumTime(double& dTurningTime, double& dOnSettlingTime, double& dOffSettlingTime);

	int GetVacuumTime(EVacuumTime eVacuumTime, double& dVacuumTime);

	int CompareIO();

	BOOL IsOn();

	BOOL IsOff();

	int On(int skip_sensor = FALSE);
	
	int Off(int skip_sensor = FALSE);

/*----------- Vacuum 동작 시작  -----------------------*/
    int StartOn();

    int StartOff();

/*----------- Vacuum 동작완료시까지 Sleep  -----------------------*/
    int Wait4OnComplete();

    int Wait4OffComplete();

	void OffSolenoid();

/*------------------------ Common Interface -----------------------*/

	int AssignComponents(IIO *pIO);

	int SetData(SVacuumData datComponent);

	int GetData(SVacuumData *pData); 

	int LoadParameter();

	int SaveParameter(MVacuumData* pvacTimerData);
	
	void GetParameter(MVacuumData* pvacParameter);

	CString GetVacuumName();

	unsigned short* GetSolAddr();

	unsigned short* GetSensorAddr();
};
#endif //Vacuum_H
