/* Generated by Together */

#ifndef MTABOFFSETDATA_H
#define MTABOFFSETDATA_H

#include "MFileManager.h"
#include "DefSystem.h"

class MTabOffsetData : public MFileManager
{
public:
	double m_rgdXuTabOffsetTabMounter[DEF_MAX_TAB_XU];
	double m_rgdXuTabOffsetTabAligner[DEF_MAX_TAB_XU];
	double m_rgdXuTabOffsetTabAlignerT[DEF_MAX_TAB_XU];

	double m_rgdXdTabOffsetTabMounter[DEF_MAX_TAB_XU];
	double m_rgdXdTabOffsetTabAligner[DEF_MAX_TAB_XU];
	double m_rgdXdTabOffsetTabAlignerT[DEF_MAX_TAB_XU];

	double m_rgdYlTabOffsetTabMounter[DEF_MAX_TAB_XU];
	double m_rgdYlTabOffsetTabAligner[DEF_MAX_TAB_XU];
	double m_rgdYlTabOffsetTabAlignerT[DEF_MAX_TAB_XU];

	double m_rgdYrTabOffsetTabMounter[DEF_MAX_TAB_XU];
	double m_rgdYrTabOffsetTabAligner[DEF_MAX_TAB_XU];
	double m_rgdYrTabOffsetTabAlignerT[DEF_MAX_TAB_XU];

private:
	void initialize();

public:
	MTabOffsetData();
    MTabOffsetData(CString strFileName, CString strPath);
    MTabOffsetData(CString strFileName);
    ~MTabOffsetData();

    BOOL ReadData();
    BOOL WriteData();

	double GetTabOffsetMounter(EWorkingSide eWorkSide, int iTabNo);
	double GetTabOffsetAligner(EWorkingSide eWorkSide, int iTabNo);
	double GetTabOffsetAlignerT(EWorkingSide eWorkSide, int iTabNo);
};
#endif //MTABOFFSETDATA_H
