/* Generated by Together */

#ifndef MRFID_H
#define MRFID_H

#include "IRFID.h"
#include "DefRFID.h"

class MRFID : public virtual ICommon, public IRFID 
{
	// Attribute
private:
	IComThread *m_plnkSerialPort;
	/** Battery State */
	int	m_bBatteryState;
	int m_iHeadNo; //Head No (1,2)
	CRITICAL_SECTION	m_Sync;

	SZigRFIDMap	m_sZigItem[DEF_MAX_RFID_ITEM];
	void	initializeItem();

public: 	
	MRFID(SCommonAttribute commonData,SRFIDRefCompList listRefComponent, SRFIDData datComponent );
	~MRFID();

	// Operation
public:
	CString ReadData(EZigItemType eZigItemType);
	int WriteData(EZigItemType eZigItemType, char *pData);

	/** Battery State 반환 */
	int GetBatteryState() { return m_bBatteryState; }

private:
	/** 
	* Frame Check Sequence를 계산하여 반환한다.
	* Frame의 선두(@헤더)부터 텍스트의 종료문자까지의 배타적 논리합을 구한
	* 8Bit의 데이터를  ASCII 코드의 2문자로 변환한 것이다.
	* @param pFrame : FCS를 계산할 Frame
	* @param pFCS : 계산된 FCS를 반환한다.
	*/
	void GetFrameCheckSequence(const char *pFrame,char *pFCS);

	/**
	* Make Request Command Format
	* @param iCommandType : Command Type
	* @param pFrameMessage : Retrieve RFID Frame Message
	* @param pData : User Defined Data Message
	* @param iHeadNo : Head Number
	* @param iStartAddress : Start Address
	* @param iDataCodeType : Data Code Specification Type
	* @param iUnitNo : Unit Number
	*/
	int MakeRequestCommand(ECommandType iCommandType,  char *pFrameMessage, const char *pData = NULL, int iHeadNo = DEF_INVALID_HEAD_NO , int iStartAddress = DEF_INVALID_START_ADDRESS,int iReadByte = DEF_INVALID_READBYTE_NO, EDataCodeSpec iDataCodeType = DEF_INVALID_CODE_SPEC, int iUnitNo = DEF_INVALID_UNIT_NO);
	
						
	/**
	* Make Response Command Format
	* @param iCommandType : Command Type
	* @param iEndCode : End Code
	* @param pFrameMessage : Retrieve RFID Frame Message
	* @param pData : User Defined Data Message
	* @param iUnitNo : Unit Number
	*/
	int MakeResponseCommand(ECommandType iCommandType, int iEndCode,   char *pFrameMessage, char *pData = NULL, int iUnitNo = DEF_INVALID_UNIT_NO);
	int ResponseCommandInterpretation (const char *pFrameMessage, char *pData = NULL, int *iUnit = NULL);

public:
	// 특수문자 처리
	CString RemoveSpecialChar(CString sRcvStr);
};
#endif //MRFID_H
